(() => {
  const $=id=>document.getElementById(id), STORAGE='hitCalcPotionsV10';
  const POTIONS=[
    ['uvPotSpeed3','Speed III','+300% Speed'],['uvPotLuck3','Luck III','+25 Luck'],
    ['uvPotLegendarySpeed','Legendary Speed','+500% Speed'],['uvPotLegendaryLuck','Legendary Luck','+40 Luck'],
    ['uvPotElixir','Elixir','×2 Luck'],['uvPotCursed','Cursed Potion','×1.5 Luck'],
    ['uvPotEventSpeed','Event Speed','×1.25 Speed'],['uvPotEventLuck','Event Luck','×1.25 Luck']
  ];
  const B={Platinum:{d:100,m:100},Crystal:{d:1e4,m:1e4},Ruby:{d:1e5,m:1e5},Galaxy:{d:1e6,m:1e6}}, BN=Object.keys(B);
  const SK={Luck:[0,15,30,45,60,75,90,150],RollSpeed:[0,5,10,15,20,25,30,45],AllStat:[0,3,6,11],Platinum:[0,.5,1,1.5,2,2.5,5],Crystal:[0,1.75,3.5,5.25,7,8.75,14.75],Ruby:[0,1.5,3,4.5,6,7.5,13.5],Galaxy:[0,4,8,12,16,20,30]};
  const CH={None:{},'Old Tome':{Luck:.5},'Holy Cross':{Luck:1},Bloodstone:{Luck:2},'Lunar Charm':{Luck:2.5,Cooldown:10},'Blood Moon':{Luck:3,Cooldown:20},'Ice Crystal':{Luck:3.5,Cooldown:30},"Victor's Trophy":{Luck:5,Cooldown:40},'Phoenix Feather':{Luck:5.5,Cooldown:50},'Hell Charm':{Luck:7.5,Cooldown:60},"Emperor's Hand":{Luck:10,Cooldown:75},'Heavenly Crown':{Luck:15,Cooldown:100},Durandal:{Luck:7,Cooldown:60},'Platinum Gem':{Luck:10,Platinum:.5,Cooldown:80},'Crystal Gem':{Luck:12,Platinum:.5,Crystal:.5,Cooldown:100},'Dark Star':{Luck:15,Platinum:.5,Crystal:.5,Ruby:.5,Galaxy:.5,Cooldown:125},'Infinity Gem':{Luck:20,Platinum:1,Crystal:1,Ruby:1,Galaxy:1,Cooldown:150},'Lucky Crown':{Luck:27,Platinum:1.5,Crystal:1.5,Ruby:1.5,Galaxy:1.5,Cooldown:175},'Forbidden Book':{Luck:35,Platinum:2,Crystal:2,Ruby:2,Galaxy:2,Cooldown:200},"Angel's Halo":{Luck:42,Platinum:3,Crystal:3,Ruby:3,Galaxy:3,Cooldown:200},'Forbidden Fruit':{Luck:50,Platinum:4,Crystal:4,Ruby:4,Galaxy:4,Cooldown:200},'Book of Life and Death':{Luck:66,Platinum:6,Crystal:6,Ruby:6,Galaxy:6,Cooldown:200}};
  const SFX=['','K','M','B','T','Qa','Qi','Sx','Sp','Oc','No','Dc'], TU={second:1,minute:60,hour:3600,day:86400,week:604800}, TH=Array.from({length:22},(_,i)=>10**(i+1));
  const on=id=>!!$(id)?.checked, num=(id,f=0)=>{const v=Number($(id)?.value);return Number.isFinite(v)?v:f}, lvl=(id,m)=>Math.max(0,Math.min(m,Math.floor(num(id))));
  const skill=(name,id)=>SK[name][lvl(id,SK[name].length-1)]||0;
  const sm=(kind,l)=>kind==='Luck'||kind==='Speed'?1+.5*l/7:1+l/5;
  function chaska(points,rate){let r=Math.max(0,Math.floor(Number(points)||0)),b=0,t=0;while(r>0){const a=Math.min(50,r);t+=a*rate*.85**b;r-=a;b++}return t}
  function stats(){
    const rolls=Math.max(0,Math.floor(num('uvRolls'))), charm=CH[$('uvCharm')?.value]||{};
    const s={Luck:skill('Luck','uvSkillLuck'),RollSpeed:skill('RollSpeed','uvSkillSpeed'),AllStat:skill('AllStat','uvSkillAll'),Platinum:skill('Platinum','uvSkillPlatinum'),Crystal:skill('Crystal','uvSkillCrystal'),Ruby:skill('Ruby','uvSkillRuby'),Galaxy:skill('Galaxy','uvSkillGalaxy')};
    const st={Luck:lvl('uvStructureLuck',7),Speed:lvl('uvStructureSpeed',7),Platinum:lvl('uvStructurePlatinum',5),Crystal:lvl('uvStructureCrystal',5),Ruby:lvl('uvStructureRuby',5),Galaxy:lvl('uvStructureGalaxy',5)};
    let luck=1+Math.floor(rolls/1e6)*.1+(charm.Luck||0);
    luck*=1+(s.Luck+s.AllStat)/100;
    if(on('uvPotLuck3'))luck+=25;if(on('uvPotLegendaryLuck'))luck+=40;if(on('uvPotCursed'))luck*=1.5;if(on('uvPotElixir'))luck*=2;if(on('uvPotEventLuck'))luck*=1.25;
    luck*=sm('Luck',st.Luck);luck+=chaska(num('uvChaskaLuck'),.25);if(on('uvQuickdraw'))luck*=.8;if(on('uvHeavyHand'))luck*=1.2;
    let speed=100+(on('uvPotSpeed3')?300:0)+(on('uvPotLegendarySpeed')?500:0)+(charm.Cooldown||0);
    speed*=1+(s.RollSpeed+s.AllStat)/100;if(on('uvPotEventSpeed'))speed*=1.25;if(on('uvQuickdraw'))speed*=1.1;if(on('uvHeavyHand'))speed*=.9;
    const cb={Platinum:chaska(num('uvChaskaPlatinum'),.05),Crystal:chaska(num('uvChaskaCrystal'),.10),Ruby:0,Galaxy:chaska(num('uvChaskaGalaxy'),.25)}, be={};
    const boost=on('uvBorderBoost')?1.5:1, all=1+s.AllStat/100;
    for(const n of BN){let base=(1+(charm[n]||0)+s[n])*all;base*=sm(n,st[n]);be[n]=base*boost+cb[n]}
    const timeStorm=on('uvTimeStorm'), cps=(speed/100)*sm('Speed',st.Speed)*(timeStorm?2:1);
    return {rolls,luck,speed,be,cps,timeStorm,boss:on('uvBossPot'),surge:on('uvLuckySurge'),dice:on('uvDice')};
  }
  const br=(n,s)=>Math.min(1,Math.max(0,s.be[n]/B[n].d));
  const cr=(names,s)=>names.reduce((r,n)=>r*br(n,s),1);
  function activeCards(s){const now=Date.now()/1000,p=typeof CARD_POOL!=='undefined'?CARD_POOL:[];return p.filter(c=>!(c.expires&&c.expires<=now)&&(!c.weather||c.weather==='Time Storm'&&s.timeStorm))}
  function luckStates(s){const u=s.surge&&s.cps>0?Math.min(1,10/(30+100/s.cps)):0,d=s.dice?1/25:0,n=1-d,a=[];if(1-u>0){a.push([1,(1-u)*n]);if(d)a.push([2,(1-u)*d])}if(u){a.push([1.25,u*n]);if(d)a.push([2.5,u*d])}return a}
  function distAt(s,m){const cards=activeCards(s),out=[];let rem=1;for(const c of cards){const rr=c.rarity*(c.rollFactor||1),bm=s.boss&&c.boss?5:1,p=Math.min(1,s.luck*m*bm/rr),hit=rem*p;if(hit>0)out.push({card:c,probability:hit});rem*=1-p;if(rem<=0)break}if(rem>0&&cards.length){const c=cards[cards.length-1],f=out.find(e=>e.card.name===c.name);f?f.probability+=rem:out.push({card:c,probability:rem})}return out}
  function distribution(s){const map=new Map;for(const [m,w] of luckStates(s))for(const e of distAt(s,m)){const f=map.get(e.card.name);f?f.probability+=e.probability*w:map.set(e.card.name,{card:e.card,probability:e.probability*w})}return [...map.values()]}
  function borderOutcomes(s){const o=[];for(let mask=0;mask<16;mask++){let p=1,m=1;for(let i=0;i<4;i++){const n=BN[i],r=br(n,s);if(mask&(1<<i)){p*=r;m*=B[n].m}else p*=1-r}if(p>0)o.push({p,m})}return o}
  function tr(t,s,d,o){if(!(t>0))return 0;let r=0;for(const e of d){let bh=0;for(const x of o)if(e.card.rarity*x.m>=t)bh+=x.p;r+=e.probability*bh}return Math.min(1,Math.max(0,r))}
  const fixed=(v,d)=>v.toFixed(d).replace(/\.0+$/,'').replace(/(\.\d*?[1-9])0+$/,'$1');
  function fn(v,dec=0){if(!Number.isFinite(v))return'—';const a=Math.abs(v);if(a<1000)return v.toLocaleString(undefined,{maximumFractionDigits:dec});const t=Math.floor(Math.log10(a)/3);if(t>=SFX.length)return v.toExponential(2);const x=v/1000**t,d=Math.abs(x)>=100?0:Math.abs(x)>=10?1:2;return`${fixed(x,d)}${SFX[t]}`}
  function ft(sec){if(!Number.isFinite(sec))return'—';if(sec<60)return`${fixed(sec,sec<10?2:1)}s`;const t=Math.round(sec),y=Math.floor(t/31557600),d=Math.floor(t%31557600/86400),h=Math.floor(t%86400/3600),m=Math.floor(t%3600/60),ss=t%60;if(y>=1000)return`${fn(y)}y`;const p=[];if(y)p.push(`${y}y`);if(d)p.push(`${d}d`);if(h)p.push(`${h}h`);if(m)p.push(`${m}m`);if(!y&&!d&&!h&&ss)p.push(`${ss}s`);return p.slice(0,3).join(' ')||'0s'}
  function fs(e){if(!Number.isFinite(e)||e<=0)return'0%';const rp=e*100;if(rp<1)return`1 / ${fn(1/e,2)}`;const p=Math.min(2000,rp);if(p>=2000)return'2000%';return p>=10?`${fixed(p,1)}%`:`${fixed(p,2)}%`}
  const selected=()=>[...document.querySelectorAll('#upgradeCalcV2 .uv-border.active')].map(b=>b.dataset.border).filter(n=>B[n]);
  function chip(n){const s=document.createElement('span');s.className=`uv-mini-chip ${n.toLowerCase()}`;s.textContent=n;return s}
  function item(labels,val,rar=false){const d=document.createElement('div');d.className='uv-chance';const l=document.createElement('div');l.className='uv-chance-label';if(rar){const c=document.createElement('span');c.className='uv-mini-chip';c.textContent=labels;l.append(c)}else labels.forEach(n=>l.append(chip(n)));const st=document.createElement('strong');st.textContent=val;d.append(l,st);return d}
  function render(){if(!$('upgradeCalcV2'))return;const s=stats(),d=distribution(s),o=borderOutcomes(s),sel=selected(),bRate=sel.length?cr(sel,s):0,bRoll=bRate>0?1/bRate:Infinity,target=Math.max(1,num('uvCardRarity',1e6)),cRate=tr(target,s,d,o),cRoll=cRate>0?1/cRate:Infinity;
    if($('uvOutLuck'))$('uvOutLuck').textContent=fn(s.luck,2);if($('uvOutSpeed'))$('uvOutSpeed').textContent=`${fn(s.speed,2)}%`;if($('uvBorderRolls'))$('uvBorderRolls').textContent=fn(bRoll);if($('uvBorderTime'))$('uvBorderTime').textContent=ft(bRoll/s.cps);if($('uvCardRolls'))$('uvCardRolls').textContent=fn(cRoll);if($('uvCardTime'))$('uvCardTime').textContent=ft(cRoll/s.cps);if($('uvCardsSecond'))$('uvCardsSecond').textContent=fn(s.cps,2);if($('uvRollsHour'))$('uvRollsHour').textContent=fn(s.cps*3600);
    const secs=Math.max(0,num('uvTimeValue',1))*(TU[$('uvTimeUnit')?.value]||3600),rolls=Math.max(0,Math.floor(secs*s.cps));if($('uvTimeRolls'))$('uvTimeRolls').textContent=fn(rolls);
    const bg=$('uvBorderChanceGrid');if(bg){bg.replaceChildren();const combos=[];for(let mask=1;mask<16;mask++){const names=[];for(let i=0;i<4;i++)if(mask&(1<<i))names.push(BN[i]);combos.push({names,rate:cr(names,s)})}combos.sort((a,b)=>a.names.length-b.names.length||b.rate-a.rate);for(const x of combos)bg.append(item(x.names,fs(x.rate*rolls)))}
    const cg=$('uvCardChanceGrid');if(cg){cg.replaceChildren();for(const t of TH)cg.append(item(`≥ ${fn(t)}`,fs(tr(t,s,d,o)*rolls),true))}
  }
  function save(){try{const v={};for(const [id] of POTIONS)v[id]=on(id);v.uvBossPot=on('uvBossPot');localStorage.setItem(STORAGE,JSON.stringify(v))}catch{}}
  function load(){try{const v=JSON.parse(localStorage.getItem(STORAGE)||'{}');for(const [id] of POTIONS)if(typeof v[id]==='boolean'&&$(id))$(id).checked=v[id];if(typeof v.uvBossPot==='boolean'&&$('uvBossPot'))$('uvBossPot').checked=v.uvBossPot}catch{}}
  function build(){const root=$('upgradeCalcV2'),row=root?.querySelector('.uv-pre-tree-row'),mods=root?.querySelector('.uv-tool-modifiers');if(!root||!row||!mods||root.querySelector('.uv-tool-potions'))return;const p=document.createElement('article');p.className='uv-panel uv-tool-potions';p.innerHTML=`<div class="uv-panel-title"><strong>Potions</strong></div><div class="uv-potion-grid">${POTIONS.map(([id,l,e])=>`<label class="uv-potion-toggle"><input id="${id}" type="checkbox"><span><strong>${l}</strong><small>${e}</small></span></label>`).join('')}</div>`;const bi=$('uvBossPot'),bl=bi?.closest('.uv-toggle');if(bl){bl.classList.remove('uv-toggle');bl.classList.add('uv-potion-toggle','uv-boss-potion-toggle');bl.querySelector('span').innerHTML='<strong>Boss Pot</strong><small>5× Boss Cards</small>';p.querySelector('.uv-potion-grid').append(bl)}row.insertBefore(p,mods);load()}
  function css(){if($('potions-v10-styles'))return;const s=document.createElement('style');s.id='potions-v10-styles';s.textContent=`#upgradeCalcV2 .uv-pre-tree-row{grid-template-columns:minmax(235px,290px) minmax(0,1fr)!important;grid-template-areas:'account potions' 'account modifiers';align-items:stretch!important}#upgradeCalcV2 .uv-tool-account{grid-area:account!important}#upgradeCalcV2 .uv-tool-potions{grid-area:potions!important;padding:14px!important;min-width:0}#upgradeCalcV2 .uv-tool-modifiers{grid-area:modifiers!important}#upgradeCalcV2 .uv-tool-potions .uv-panel-title{margin-bottom:9px!important}#upgradeCalcV2 .uv-tool-potions .uv-panel-title strong{font-size:.78rem;text-transform:uppercase;letter-spacing:.075em;color:var(--muted)}#upgradeCalcV2 .uv-potion-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}#upgradeCalcV2 .uv-potion-toggle{position:relative;display:block;min-width:0}#upgradeCalcV2 .uv-potion-toggle>input{position:absolute;opacity:0;pointer-events:none}#upgradeCalcV2 .uv-potion-toggle>span{display:flex;flex-direction:column;justify-content:center;min-height:47px;padding:7px 9px;border:1px solid var(--line);border-radius:9px;background:var(--panel-2);cursor:pointer;min-width:0}#upgradeCalcV2 .uv-potion-toggle strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#c9d0da;font-size:.66rem}#upgradeCalcV2 .uv-potion-toggle small{margin-top:3px;color:#717b89;font-size:.54rem;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#upgradeCalcV2 .uv-potion-toggle>input:checked+span{border-color:color-mix(in srgb,var(--blue) 68%,var(--line));background:color-mix(in srgb,var(--blue) 9%,var(--panel-2))}#upgradeCalcV2 .uv-potion-toggle>input:checked+span strong{color:#fff}#upgradeCalcV2 .uv-potion-toggle>input:checked+span small{color:var(--blue)}#upgradeCalcV2 .uv-boss-potion-toggle>input:checked+span{border-color:color-mix(in srgb,var(--ruby) 58%,var(--line));background:color-mix(in srgb,var(--ruby) 8%,var(--panel-2))}#upgradeCalcV2 .uv-pre-tree-row .uv-tool-modifiers .uv-toggle-grid{grid-template-columns:repeat(3,minmax(0,1fr))!important}@media(max-width:1120px){#upgradeCalcV2 .uv-potion-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:760px){#upgradeCalcV2 .uv-pre-tree-row{grid-template-columns:1fr!important;grid-template-areas:'account' 'potions' 'modifiers'}#upgradeCalcV2 .uv-potion-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}`;document.head.append(s)}
  let q=false;function qr(){if(q)return;q=true;queueMicrotask(()=>{q=false;render();save()})}
  function bind(){const r=$('upgradeCalcV2');if(!r)return;r.addEventListener('input',qr);r.addEventListener('change',qr);r.addEventListener('click',e=>{if(e.target.closest('.uv-border,.uv-tree-node,.uv-chaska-controls,[data-time-mode]'))qr()});$('resetBtn')?.addEventListener('click',()=>{if(getComputedStyle(r).display==='none')return;try{localStorage.removeItem(STORAGE)}catch{}setTimeout(()=>{for(const [id] of POTIONS)if($(id))$(id).checked=false;if($('uvBossPot'))$('uvBossPot').checked=false;render()},0)})}
  function init(){if(!$('upgradeCalcV2'))return;css();build();bind();render()}
  if(document.readyState==='complete')init();else window.addEventListener('load',init,{once:true});
})();
